--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/DavidFlashCZ/FlashItem
build-by-default: true
branches:
- master
projects:
  FlashItem:
    path: ""
    libs:
      - src: jojoe77777/FormAPI/libFormAPI
        version: ^1.3.0
...
